[ general ]
live_config_reload = true

[ window ]
option_as_alt = "Both"

[ font ]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
bold = { family = "MesloLGS Nerd Font", style = "Bold" }
italic = { family = "MesloLGS Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic" }
size = 12.0
